# Override configuration from https://github.com/jenkins-x/jenkins-x-platform/blob/master/jenkins-x-platform/values.yaml
docker-registry:
  enabled: false

nexus:
  enabled: false

# Configure Docker secret to push images to docker.io            
PipelineSecrets:
  DockerConfig: |-
      {
        "auths": {
          "registry-internal.g3rg.org": {
            "auth": "YWRtaW46SGFyYm9yMTIzNDU="
          }
        },
        "HttpHeaders": {
          "User-Agent": "Docker-Client/18.09.7 (linux)"
        }
      }
